version: '3.8'
services:
  modelscope:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HTTP_PROXY: ${HTTP_PROXY}
    image: paidax/dev-containers:modelscope-cuda11.7-py3.8-v0.4
    container_name: modelscope
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - 9999:9999
    command: tail -f /dev/null
